export const POST_ALBUM_DATA_REQUEST = "POST_ALBUM_DATA_REQUEST"
export const ALBUM_DATA_REQUEST_SUCCESS = "ALBUM_DATA_REQUEST_SUCCESS"
export const ALBUM_DATA_REQUEST_FAILURE = "ALBUM_DATA_REQUEST_FAILURE"